[tool.poetry]
name = "montyhallconundrum"
version = "0.1.0"
description = ""
authors = ["zypherion <zxcbvnm90@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
threaded = "^4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
